export default [
  { title: "Chrome", name: "chrome", color: "#ebebeb" },
  { title: "Ambiance", name: "ambiance", color: "#3d3d3d" },
  { title: "Chaos", name: "chaos", color: "#141414" },
  { title: "Clouds midnight", name: "clouds_midnight", color: "#232323" },
  { title: "Clouds", name: "clouds", color: "#ebebeb" },
  { title: "Cobalt", name: "cobalt", color: "#011e3a" },
  { title: "Crimson editor", name: "crimson_editor", color: "#ebebeb" },
  { title: "Dawn", name: "dawn", color: "#ebebeb" },
  { title: "Dracula", name: "dracula", color: "#282a36" },
  { title: "Dreamweaver", name: "dreamweaver", color: "#e8e8e8" },
  { title: "Eclipse", name: "eclipse", color: "#ebebeb" },
  { title: "Github", name: "github", color: "#e8e8e8" },
  { title: "Gob", name: "gob", color: "#0B1818" },
  { title: "Gruvbox", name: "gruvbox", color: "#3C3836" },
  { title: "Idle fingers", name: "idle_fingers", color: "#3b3b3b" },
  { title: "Iplastic", name: "iplastic", color: "#dddddd" },
  { title: "Katzenmilch", name: "katzenmilch", color: "#e8e8e8" },
  { title: "Kr theme", name: "kr_theme", color: "#1c1917" },
  { title: "Kuroir", name: "kuroir", color: "#e8e8e8" },
  { title: "Merbivore soft", name: "merbivore_soft", color: "#262424" },
  { title: "Merbivore", name: "merbivore", color: "#202020" },
  { title: "Mono industrial", name: "mono_industrial", color: "#1d2521" },
  { title: "Monokai", name: "monokai", color: "#2F3129" },
  { title: "Pastel on dark", name: "pastel_on_dark", color: "#353030" },
  { title: "Solarized dark", name: "solarized_dark", color: "#01313f" },
  { title: "Solarized light", name: "solarized_light", color: "#fbf1d3" },
  { title: "Sqlserver", name: "sqlserver", color: "#ebebeb" },
  { title: "Terminal", name: "terminal", color: "#1a0005" },
  { title: "Textmate", name: "textmate", color: "#f0f0f0" },
  {
    title: "Tomorrow night blue",
    name: "tomorrow_night_blue",
    color: "#00204b",
  },
  {
    title: "Tomorrow night bright",
    name: "tomorrow_night_bright",
    color: "#1a1a1a",
  },
  {
    title: "Tomorrow night eighties",
    name: "tomorrow_night_eighties",
    color: "#272727",
  },
  { title: "Tomorrow night", name: "tomorrow_night", color: "#25282c" },
  { title: "Tomorrow", name: "tomorrow", color: "#f6f6f6" },
  { title: "Twilight", name: "twilight", color: "#232323" },
  { title: "Vibrant ink", name: "vibrant_ink", color: "#1a1a1a" },
];
